SRC = File.o Catalog.o Serializer.o
Final: Project_UI.cpp File Catalog Serializer
	g++ -o Final Project_UI.cpp $(SRC)
File: File.cpp
	g++ -c File.cpp
Catalog: Catalog.cpp
	g++ -c Catalog.cpp
Serializer: Serializer.cpp
	g++ -c Serializer.cpp

clean:
	rm *.o Final
